/*
 * Copyright (c) 2026, Roel
 * All rights reserved.
 * Licensed under the BSD 2-Clause License. See LICENSE for details.
 */
package com.pohtemplates.data;

import com.google.gson.Gson;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

/**
 * Guards the bundled data file. It is generated by tools/build_data.py, and these checks are what
 * stop a bad regeneration from shipping.
 */
public class PohDataTest
{
	private PohData data;

	@Before
	public void setUp()
	{
		data = new PohDataService(new Gson()).get();
	}

	@Test
	public void loadsTheBundledData()
	{
		assertFalse("rooms.json did not load", data.isEmpty());
		assertFalse(data.getStyles().isEmpty());
		assertFalse(data.getItems().isEmpty());
	}

	@Test
	public void everyRoomIsUsable()
	{
		Set<String> roomIds = new HashSet<>();
		for (RoomDef room : data.getRooms())
		{
			assertNotNull(room.getId());
			assertTrue("duplicate room id " + room.getId(), roomIds.add(room.getId()));
			assertNotNull("room " + room.getId() + " has no name", room.getName());
			assertTrue("room " + room.getId() + " has no plane", !room.getPlanes().isEmpty());
			assertTrue("room " + room.getId() + " has an odd level", room.getLevel() >= 1 && room.getLevel() <= 99);
			assertFalse("room " + room.getId() + " has no hotspots", room.getHotspots().isEmpty());

			Set<String> hotspotIds = new HashSet<>();
			for (HotspotDef hotspot : room.getHotspots())
			{
				assertNotNull(hotspot.getId());
				assertTrue("duplicate hotspot " + hotspot.getId() + " in " + room.getId(),
					hotspotIds.add(hotspot.getId()));
				assertFalse("hotspot " + room.getId() + "/" + hotspot.getId() + " has no object ids",
					hotspot.getObjectIds().isEmpty());
				assertFalse("hotspot " + room.getId() + "/" + hotspot.getId() + " has nothing to build",
					hotspot.getOptions().isEmpty());

				Set<String> optionIds = new HashSet<>();
				for (FurnitureDef option : hotspot.getOptions())
				{
					assertNotNull(option.getId());
					assertTrue("duplicate furniture " + option.getId() + " in " + hotspot.getId(),
						optionIds.add(option.getId()));
					assertTrue("furniture " + option.getId() + " has an odd level",
						option.getLevel() >= 1 && option.getLevel() <= 99);
					assertTrue("furniture " + option.getId() + " has negative xp", option.getXp() >= 0);
				}
			}
		}
	}

	@Test
	public void everyMaterialIsDescribed()
	{
		for (RoomDef room : data.getRooms())
		{
			for (HotspotDef hotspot : room.getHotspots())
			{
				for (FurnitureDef option : hotspot.getOptions())
				{
					for (Material material : option.getMaterials())
					{
						assertTrue("furniture " + option.getId() + " asks for a non-positive quantity",
							material.getQuantity() > 0);
						assertNotNull("no item entry for item " + material.getItemId()
								+ " used by " + option.getId(),
							data.getItem(material.getItemId()));
					}
				}
			}
		}
	}

	@Test
	public void objectIdsResolveBackToTheirHotspot()
	{
		for (RoomDef room : data.getRooms())
		{
			for (HotspotDef hotspot : room.getHotspots())
			{
				for (Integer objectId : hotspot.getObjectIds())
				{
					List<ObjectRef> refs = data.getObjectRefs(objectId);
					assertFalse("object " + objectId + " did not index", refs.isEmpty());

					boolean found = false;
					for (ObjectRef ref : refs)
					{
						if (ref.getRoom() == room && ref.getHotspot() == hotspot && ref.isEmptyHotspot())
						{
							found = true;
							break;
						}
					}
					assertTrue("object " + objectId + " does not point back at "
						+ room.getId() + "/" + hotspot.getId(), found);
				}
			}
		}
	}

	@Test
	public void aHotspotObjectIsNeverAlsoBuiltFurniture()
	{
		Set<Integer> hotspotObjects = new HashSet<>();
		Set<Integer> furnitureObjects = new HashSet<>();

		for (RoomDef room : data.getRooms())
		{
			for (HotspotDef hotspot : room.getHotspots())
			{
				hotspotObjects.addAll(hotspot.getObjectIds());
				for (FurnitureDef option : hotspot.getOptions())
				{
					furnitureObjects.addAll(option.getObjectIds());
				}
			}
		}

		Set<Integer> overlap = new HashSet<>(hotspotObjects);
		overlap.retainAll(furnitureObjects);
		assertEquals("these object ids are both an empty hotspot and built furniture: " + overlap,
			0, overlap.size());
	}

	@Test
	public void roomColoursParse()
	{
		for (RoomDef room : data.getRooms())
		{
			assertNotNull("room " + room.getId() + " has an unreadable colour", room.toAwtColour());
		}
	}

	@Test
	public void rotatingADoorFourTimesReturnsIt()
	{
		for (Direction direction : Direction.values())
		{
			assertEquals(direction, direction.rotate(4));
			assertEquals(direction.opposite(), direction.rotate(2));
		}
	}
}
